# Generated by Django 5.0.4 on 2024-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterData2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BOD", models.FloatField()),
                ("COD", models.FloatField()),
                ("month", models.IntegerField()),
            ],
        ),
    ]
